apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db

    spec:
      containers:
      - name: redis-helper
        image: gcr.io/amira-gcp/redis
        ports:
        - containerPort: 6379

---


apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
  
  - port: 6379
    targetPort: 6379